import { hashDocument } from '@motion-engine/core';

import { CompilationProfileSchema, type CompilationProfile } from './contracts.ts';

export const SHORT_FORM_DEFAULT_PROFILE: CompilationProfile = CompilationProfileSchema.parse({
  schema: 'creative-compilation-profile',
  schema_version: '0.1.0',
  id: 'short_form_default',
  version: '0.1.0',
  motion_spec_target: '0.2.0',
  fps: 30,
  system: { id: 'statement.interrupt', version: '0.1.0' },
  platform: 'shorts',
  visual_modes: {
    text_dominant: 'text_stack',
    image_dominant: 'image_hero',
    mixed: 'split',
    abstract: 'abstract',
    diagram: 'diagram',
    statistic: 'text_stack',
    quote: 'text_stack',
    comparison: 'comparison',
    reveal: 'image_hero',
    background_visual: 'image_hero',
    iconographic: 'split',
  },
  motion_characters: {
    subtle: { text_behavior: 'REVEAL_TEXT', image_behavior: 'CAMERA_PUSH', intensity_scale: 0.45 },
    energetic: { text_behavior: 'REVEAL_TEXT', image_behavior: 'CAMERA_PUSH', intensity_scale: 0.85 },
    dramatic: { text_behavior: 'REVEAL_TEXT', image_behavior: 'FOCUS_REGION', intensity_scale: 0.8 },
    playful: { text_behavior: 'REVEAL_TEXT', image_behavior: 'CAMERA_PUSH', intensity_scale: 0.75 },
    precise: { text_behavior: 'REVEAL_TEXT', image_behavior: null, intensity_scale: 0.45 },
    cinematic: { text_behavior: 'REVEAL_TEXT', image_behavior: 'CAMERA_PUSH', intensity_scale: 0.65 },
    restrained: { text_behavior: 'REVEAL_TEXT', image_behavior: null, intensity_scale: 0.35 },
    punchy: { text_behavior: 'REVEAL_TEXT', image_behavior: 'CAMERA_PUSH', intensity_scale: 0.9 },
  },
  typography_roles: {
    display: 'type.display.xl',
    headline: 'type.display.l',
    body: 'type.body',
    caption: 'type.subtitle',
    statistic: 'type.display.xl',
    quote: 'type.display.m',
    cta: 'type.headline',
  },
  transitions: {
    cut: { boundary_behavior: 'CUT', scene_reveal_behavior: null, fidelity: 'exact' },
    smooth: { boundary_behavior: 'CUT', scene_reveal_behavior: null, fidelity: 'degraded' },
    energetic: { boundary_behavior: 'CUT', scene_reveal_behavior: null, fidelity: 'degraded' },
    dramatic: { boundary_behavior: 'CUT', scene_reveal_behavior: null, fidelity: 'degraded' },
    reveal: { boundary_behavior: 'CUT', scene_reveal_behavior: 'MASK_WIPE', fidelity: 'degraded' },
    continuation: { boundary_behavior: 'CUT', scene_reveal_behavior: null, fidelity: 'degraded' },
  },
  rhythm_roles: {
    hook: 'INTERRUPTION',
    premise: 'BUILD',
    setup: 'CALM',
    context: 'CALM',
    problem: 'BUILD',
    consequence: 'ACCELERATE',
    development: 'BUILD',
    escalation: 'ACCELERATE',
    explanation: 'CALM',
    example: 'BUILD',
    item: 'BUILD',
    strongest_item: 'ACCELERATE',
    comparison_a: 'BUILD',
    comparison_b: 'BUILD',
    contrast: 'REVEAL',
    solution: 'REVEAL',
    demonstration: 'BUILD',
    action: 'ACCELERATE',
    result: 'REVEAL',
    proof: 'REVEAL',
    tension: 'BUILD',
    partial_information: 'BUILD',
    reveal: 'REVEAL',
    payoff: 'RESOLUTION',
    takeaway: 'RESOLUTION',
    cta: 'RESOLUTION',
  },
  scene_purposes: {
    hook: 'hook',
    premise: 'tension',
    setup: 'tension',
    context: 'proof',
    problem: 'tension',
    consequence: 'tension',
    development: 'proof',
    escalation: 'tension',
    explanation: 'proof',
    example: 'proof',
    item: 'proof',
    strongest_item: 'reveal',
    comparison_a: 'proof',
    comparison_b: 'proof',
    contrast: 'reveal',
    solution: 'reveal',
    demonstration: 'proof',
    action: 'proof',
    result: 'reveal',
    proof: 'proof',
    tension: 'tension',
    partial_information: 'tension',
    reveal: 'reveal',
    payoff: 'resolution',
    takeaway: 'resolution',
    cta: 'cta',
  },
});

export function compilationProfileFingerprint(profile: CompilationProfile): string {
  return hashDocument(CompilationProfileSchema.parse(profile));
}
